server:
  port: 8080
eureka:
  instance:
    hostname: localhost


spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**


        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product/**


        - id: bill-service
          uri: lb://bill-service
          predicates:
            - Path=/api/bill/**






