server:
    port: 8081

spring:
  application:
    name:  user-service

  datasource:
         driverClassName: com.mysql.jdbc.Driver
         url: jdbc:mysql://localhost:3306/store_discounts_application?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
         username: root
         password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
         dialect: org.hibernate.dialect.MySQL5Dialect

